name: flutterfirebase
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
firebase_auth: ^0.15.5+2
provider: ^4.0.4

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:

  
  uses-material-design: true

 